[[pages]]
path = "pages/about.py"
name = "Acceuil"
icon = "ğŸ "

[[pages]]
path = "pages/app.py"
name = "Application"
icon = "ğŸ¿"

[[pages]]
path = "pages/KPI.py"
name = "KPI"
icon = "ğŸ“Š"

[[pages]]
path = "pages/contact.py"
name = "Contact"
icon = "ğŸ’Œ"

[[pages]]
path = "pages/todo.py"
name = "Todo"
icon = "ğŸ› ï¸"
url_path = "todo.py"